Repository SpaceVim/SpaceVim, pull requests merged in 2018-02, with the labels that each got.

#1399 Map [SPC]is to Unite ultisnips while using Ultisnips engine
  autoload/SpaceVim/layers/autocomplete.vim
Labels: WIP

#1406 Relicense
  CONTRIBUTING.md
  LICENSE
  README.cn.md
  README.md
  autoload/SpaceVim.vim
  autoload/SpaceVim/api.vim
  autoload/SpaceVim/api/vim/message.vim
  autoload/SpaceVim/api/vim/sid.vim
  autoload/SpaceVim/autocmds.vim
  autoload/SpaceVim/layers/core/statusline.vim
  autoload/SpaceVim/layers/core/tabline.vim
  autoload/SpaceVim/layers/format.vim
  autoload/SpaceVim/layers/github.vim
  autoload/SpaceVim/layers/lang/json.vim
  autoload/SpaceVim/layers/lang/julia.vim
  autoload/SpaceVim/layers/lang/markdown.vim
  autoload/SpaceVim/layers/lang/php.vim
  autoload/SpaceVim/layers/lang/pony.vim
  autoload/SpaceVim/layers/lang/ruby.vim
  autoload/SpaceVim/layers/lang/typescript.vim
  autoload/SpaceVim/layers/tools/dash.vim
  autoload/SpaceVim/lsp.vim
  autoload/SpaceVim/mapping/guide.vim
  autoload/SpaceVim/mapping/leader.vim
  autoload/SpaceVim/plugins/flygrep.vim
  autoload/SpaceVim/plugins/highlight.vim
  autoload/SpaceVim/plugins/iedit.vim
  autoload/SpaceVim/plugins/manager.vim
  autoload/SpaceVim/plugins/pmd.vim
  autoload/SpaceVim/plugins/projectmanager.vim
  autoload/SpaceVim/plugins/repl.vim
  autoload/SpaceVim/plugins/runner.vim
  autoload/SpaceVim/server.vim
  autoload/airline/extensions/tabline/formatters/spacevim.vim
  autoload/leaderf/colorscheme/spacevim.vim
  bin/nsvc
  bin/svc
  config/main.vim
  docs/cn/development.md
  docs/cn/index.md
  docs/cn/install.sh
  docs/development.md
  docs/index.md
  docs/install.sh
  init.vim
  vimrc
Labels: WIP

#1404 Supporting eex in the elixir layer
  autoload/SpaceVim/layers/lang/elixir.vim
Labels: WIP

#1415 Improve javascript layer
  autoload/SpaceVim/layers/lang/javascript.vim
Labels: WIP

#1413 Fix c layer
  autoload/SpaceVim/layers/lang/c.vim
Labels: WIP

#1416 Improve lint status in statusline
  autoload/SpaceVim/layers/core/statusline.vim
Labels: WIP

#1419 Improve json layer
  autoload/SpaceVim/layers/lang/json.vim
Labels: WIP

#1420 Fix github layer
  autoload/SpaceVim/layers/github.vim
Labels: WIP

#1417 Update quick start guide
  README.cn.md
  README.md
  docs/cn/quick-start-guide.md
  docs/quick-start-guide.md
Labels: WIP

#1423 Update readme
  README.md
Labels: WIP

#1424 Disable cursor error info
  autoload/SpaceVim/layers/checkers.vim
  config/plugins/neosnippet.vim
Labels: WIP

#1421 Improve javascript
  autoload/SpaceVim/layers/lang/javascript.vim
Labels: WIP, need help

#1426 Improve flygrep
  autoload/SpaceVim/api/prompt.vim
  autoload/SpaceVim/layers/core/statusline.vim
  autoload/SpaceVim/plugins/flygrep.vim
  syntax/SpaceVimFlyGrep.vim
Labels: WIP

#1429 close terminal buffer just like a regular buffer
  autoload/SpaceVim/mapping.vim
Labels: Feature Requesting, WIP

#1432 Update sponsors
  docs/cn/sponsors.md
  docs/sponsors.md
Labels: WIP

#1437 Add package.json as project rooter in javascript layer
  autoload/SpaceVim/layers/lang/javascript.vim
Labels: WIP

#1442 fix several spelling errors
  autoload/SpaceVim/layers/autocomplete.vim
  autoload/SpaceVim/layers/core.vim
  autoload/SpaceVim/layers/default.vim
  docs/documentation.md
Labels: WIP

#1443 fix layers html table
  docs/layers/index.md
Labels: WIP

#1438 Better default
  README.md
  autoload/SpaceVim.vim
  autoload/SpaceVim/api/bash/complete.vim
  autoload/SpaceVim/api/data/list.vim
  autoload/SpaceVim/custom.vim
  autoload/SpaceVim/default.vim
  autoload/SpaceVim/health/python.vim
  autoload/SpaceVim/layers/autocomplete.vim
  autoload/SpaceVim/layers/colorscheme.vim
  autoload/SpaceVim/mapping/guide/theme/SpaceVim.vim
  autoload/SpaceVim/plugins/flygrep.vim
  autoload/SpaceVim/plugins/highlight.vim
  autoload/zvim/util.vim
  codecov.yml
  colors/SpaceVim.vim
  config/init.vim
  config/main.vim
  config/plugins/neosnippet.vim
  doc/SpaceVim.cnx
  doc/SpaceVim.txt
  docs/conventions.md
  docs/development.md
  docs/layers/index.md
  test/init.vader
Labels: WIP
